version: '2'
services:
  authorizationservice:
    container_name: authorizationservice
    image: authorizationservice
    build: ./authorization-service/
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgesqldb:5432/authorizationDB
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_DATASOURCE_DRIVERCLASSNAME: org.postgresql.Driver
    ports:
      - "8080:8080"
    depends_on:
      - postgesqldb

  hashtranslatorservice:
    container_name: hashtranslatorService
    image: hashtranslatorservice
    build: ./hashtranslator-service/
    ports:
        - "8090:8090"
    depends_on:
        - mongodb

  postgesqldb:
    image: postgres:13
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=authorizationDB

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_DATABASE=hashtranslatorDB